package com.github.phweda.mfm.ui.component.validation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class ValidationBase {
  private JPanel pnlValidationMsgHolder;
  private JLabel lblValidationMsg;
  private UiMessageSeverity severity = null;
  private JPanel panelComponentHolder;

  public void setPanelComponentHolder(JPanel panelComponentHolder) {
    this.panelComponentHolder = panelComponentHolder;
  }

  public void clearMessage() {
    severity = null;
    lblValidationMsg.setText("");
    panelComponentHolder.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
  }

  public boolean setMessage(String text, UiMessageSeverity messageSeverity) {
    if (!UiMessageSeverity.higherSeverity(this.severity, messageSeverity)) {
      return false;
    }
    lblValidationMsg.setText(text);
    this.severity = messageSeverity;
    switch (messageSeverity) {
      case ERROR:
        lblValidationMsg.setForeground(Color.RED);
        panelComponentHolder.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        break;
      case WARNING:
        lblValidationMsg.setForeground(Color.ORANGE);
        panelComponentHolder.setBorder(BorderFactory.createLineBorder(Color.ORANGE, 2));
        break;
      default:
        throw new RuntimeException("Unknown severity: " + messageSeverity);
    }
    return true;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    pnlValidationMsgHolder = new JPanel();
    pnlValidationMsgHolder.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
    lblValidationMsg = new JLabel();
    lblValidationMsg.setText("");
    pnlValidationMsgHolder.add(lblValidationMsg, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer1 = new Spacer();
    pnlValidationMsgHolder.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return pnlValidationMsgHolder;
  }

}
