/*
 * MAME FILE MANAGER - MAME resources management tool
 * Copyright (c) 2011 - 2018.  Author phweda : phweda1@yahoo.com
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 07:22:36 PM EDT 
//


package com.github.phweda.MFM.datafile;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="plugin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rommode" default="split">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="merged"/>
 *             &lt;enumeration value="split"/>
 *             &lt;enumeration value="unmerged"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="biosmode" default="split">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="merged"/>
 *             &lt;enumeration value="split"/>
 *             &lt;enumeration value="unmerged"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="samplemode" default="merged">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="merged"/>
 *             &lt;enumeration value="unmerged"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lockrommode" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lockbiosmode" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="locksamplemode" default="no">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@SuppressWarnings("WeakerAccess")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "romcenter")
public class Romcenter {

    @XmlAttribute(name = "plugin")
    protected String plugin;
    @XmlAttribute(name = "rommode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rommode;
    @XmlAttribute(name = "biosmode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String biosmode;
    @XmlAttribute(name = "samplemode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String samplemode;
    @XmlAttribute(name = "lockrommode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lockrommode;
    @XmlAttribute(name = "lockbiosmode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lockbiosmode;
    @XmlAttribute(name = "locksamplemode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String locksamplemode;

    /**
     * Gets the value of the plugin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * Sets the value of the plugin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlugin(String value) {
        this.plugin = value;
    }

    /**
     * Gets the value of the rommode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRommode() {
        if (rommode == null) {
            return "split";
        } else {
            return rommode;
        }
    }

    /**
     * Sets the value of the rommode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRommode(String value) {
        this.rommode = value;
    }

    /**
     * Gets the value of the biosmode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBiosmode() {
        if (biosmode == null) {
            return "split";
        } else {
            return biosmode;
        }
    }

    /**
     * Sets the value of the biosmode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBiosmode(String value) {
        this.biosmode = value;
    }

    /**
     * Gets the value of the samplemode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSamplemode() {
        if (samplemode == null) {
            return "merged";
        } else {
            return samplemode;
        }
    }

    /**
     * Sets the value of the samplemode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSamplemode(String value) {
        this.samplemode = value;
    }

    /**
     * Gets the value of the lockrommode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLockrommode() {
        if (lockrommode == null) {
            return "no";
        } else {
            return lockrommode;
        }
    }

    /**
     * Sets the value of the lockrommode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLockrommode(String value) {
        this.lockrommode = value;
    }

    /**
     * Gets the value of the lockbiosmode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLockbiosmode() {
        if (lockbiosmode == null) {
            return "no";
        } else {
            return lockbiosmode;
        }
    }

    /**
     * Sets the value of the lockbiosmode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLockbiosmode(String value) {
        this.lockbiosmode = value;
    }

    /**
     * Gets the value of the locksamplemode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLocksamplemode() {
        if (locksamplemode == null) {
            return "no";
        } else {
            return locksamplemode;
        }
    }

    /**
     * Sets the value of the locksamplemode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLocksamplemode(String value) {
        this.locksamplemode = value;
    }

}
