/*
 * MAME FILE MANAGER - MAME resources management tool
 * Copyright (c) 2011 - 2018.  Author phweda : phweda1@yahoo.com
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 10:16:00 AM EDT 
//


package com.github.phweda.mfm.mame;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="status" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="emulation" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="color" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sound" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="graphic" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="cocktail">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="protection">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="good"/>
 *             &lt;enumeration value="imperfect"/>
 *             &lt;enumeration value="preliminary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="savestate" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="supported"/>
 *             &lt;enumeration value="unsupported"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * <p>
 * DEVELOPER NOTE: This class, among several others, retains code from previous MAME versions to keep<br/>
 * MFM backward compatible
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
/*
@XmlType(name = "", propOrder = {
        "status",
        "emulation",
        "color",
        "colordeep",
        "sound",
        "hiscore",
        "graphic",
        "cocktail",
        "protection",
        "savestate",
        "unknownElements"
})
*/
@XmlRootElement(name = "driver")
public class Driver {

    @XmlAttribute(name = "status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlAttribute(name = "emulation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String emulation;
    @XmlAttribute(name = "color", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String color;
    @XmlAttribute(name = "sound", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sound;
    @XmlAttribute(name = "graphic", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String graphic;
    @XmlAttribute(name = "cocktail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cocktail;
    @XmlAttribute(name = "protection")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String protection;
    @XmlAttribute(name = "savestate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String savestate;

    // Psuedo XML to handle entry in very old MAME versions
    @XmlAttribute(name = "colordeep", required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String colordeep;

    // Psuedo XML to handle entry in very old MAME versions
    @XmlAttribute(name = "hiscore", required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hiscore;

    // Catchall for any unknown Elements. As MAME DTD changes this will allow for
    // continuation of MFM without a code change. BUT IS NOT RECOMMENDED.
    // Addition of Elements and Attributes should be handled with code updates.
    @XmlAnyElement(lax = true)
    private List<Object> unknownElements;

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the emulation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmulation() {
        return emulation;
    }

    /**
     * Sets the value of the emulation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmulation(String value) {
        this.emulation = value;
    }

    /**
     * Gets the value of the color property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the sound property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSound(String value) {
        this.sound = value;
    }

    /**
     * Gets the value of the graphic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGraphic() {
        return graphic;
    }

    /**
     * Sets the value of the graphic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGraphic(String value) {
        this.graphic = value;
    }

    /**
     * Gets the value of the cocktail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCocktail() {
        return cocktail;
    }

    /**
     * Sets the value of the cocktail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCocktail(String value) {
        this.cocktail = value;
    }

    /**
     * Gets the value of the protection property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProtection() {
        return protection;
    }

    /**
     * Sets the value of the protection property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProtection(String value) {
        this.protection = value;
    }

    /**
     * Gets the value of the savestate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSavestate() {
        return savestate;
    }

    /**
     * Sets the value of the savestate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSavestate(String value) {
        this.savestate = value;
    }

    // Psuedo XML to handle entry in very old MAME versions

    /**
     * Gets the value of the colordeep property.
     *
     * @return object is
     * {@link String }
     */
    public String getColordeep() {
        return colordeep;
    }

    /**
     * Sets the value of the colordeep property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColordeep(String value) {
        this.colordeep = value;
    }

    // Psuedo XML to handle entry in very old MAME versions

    /**
     * Gets the value of the hiscore property.
     *
     * @return object is
     * {@link String }
     */
    public String getHiscore() {
        return hiscore;
    }

    /**
     * Sets the value of the colordeep property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHiscore(String value) {
        this.colordeep = value;
    }

}
